spring:
  application:
    name: userService
  datasource:
    url:jdbc: mysql://localhost:3306/tomato_note
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 10500
mybatis:
  mapper-locations: classpath:/mapper/*.xml